project:
  type: website
  output-dir: docs

website:
  title: "Theory of Statistical Inference"
  navbar:
    background: primary
    search: true
    logo: "images/lummi_curiosity_discovery_crop.png"
    foreground: "#fff"
    collapse-below: sm
    right:
      - schedule.qmd
      - href: syllabus.qmd
        text: Syllabus
      - href: instructors.qmd
        text: Instructor
      - href: homeworks.qmd
        text: Homework

execute:
  freeze: auto

format:
  html:
    theme:
      - sandstone_NW_JM.scss
    toc: true

